### ISSUE TITLE
AttributeError: '_io.BufferedReader' object has no attribute 'status'

### ISSUE THREAD

**Issue by job** [irrdnet/irrd#416]
empty database, version a6af0f7ff71a135ad991d7c3204b70025d1486ce

```
(irrd-venv) bench$ irrd --config /home/irrd/irrd-test.yaml
(irrd-venv) bench$ 2020-11-16 11:51:51,297 irrd[7647]: [irrd.daemon.main#INFO] IRRd attempting to secure PID
2020-11-16 11:51:51,298 irrd[7647]: [irrd.daemon.main#INFO] IRRd 4.2.0-dev starting, PID 7647, PID file in /home/irrd/
2020-11-16 11:51:51,312 irrd[33763]: [irrd.server.whois.server#INFO] Starting whois server on TCP ('::1', 4343)
2020-11-16 11:51:51,315 irrd[89583]: [irrd.server.http.server#INFO] Starting http server on TCP ('::1', 4380)
2020-11-16 11:51:51,323 irrd[90319]: [root#INFO] Starting preload store manager
2020-11-16 11:51:51,558 irrd[84628]: [irrd.mirroring.mirror_runners_import#INFO] Running full ROA import from: https://rpki.gin.ntt.net/api/export.json, SLURM None
2020-11-16 11:51:51,705 irrd[66830]: [irrd.mirroring.mirror_runners_import#INFO] Running full RPSL import of IDNIC from ['ftp://irr-mirror.idnic.net/idnic.db.gz'], serial from ftp://irr-mirror.idnic.net//IDNIC.CURRENTSERIAL
2020-11-16 11:51:51,820 irrd[2665]: [irrd.mirroring.mirror_runners_export#INFO] Starting a source export for IDNIC to /home/irrd/dumps/
2020-11-16 11:51:51,911 irrd[2665]: [irrd.mirroring.mirror_runners_export#INFO] Export for IDNIC complete at serial None, stored in /home/irrd/dumps/idnic.db.gz / /home/irrd/dumps/IDNIC.CURRENTSERIAL
2020-11-16 11:51:51,967 irrd[90319]: [irrd.storage.preload#INFO] Completed updating preload store from thread <PreloadUpdater(Thread-1, started 4615364646464)>
2020-11-16 11:51:53,577 irrd[66830]: [irrd.mirroring.mirror_runners_import#ERROR] An exception occurred while attempting a mirror update or initial import for IDNIC: '_io.BufferedReader' object has no attribute 'status'
Traceback (most recent call last):
  File "/home/irrd/src/irrd/mirroring/mirror_runners_import.py", line 50, in run
    self.full_import_runner.run(database_handler=self.database_handler,
  File "/home/irrd/src/irrd/mirroring/mirror_runners_import.py", line 199, in run
    import_serial = int(self._retrieve_file(import_serial_source, return_contents=True)[0])
  File "/home/irrd/src/irrd/mirroring/mirror_runners_import.py", line 95, in _retrieve_file
    return self._retrieve_file_download(url, url_parsed, return_contents)
  File "/home/irrd/src/irrd/mirroring/mirror_runners_import.py", line 118, in _retrieve_file_download
    self._download_file(destination, url, url_parsed)
  File "/home/irrd/src/irrd/mirroring/mirror_runners_import.py", line 146, in _download_file
    if r.status == 200:
  File "/home/irrd/irrd-venv/lib/python3.8/tempfile.py", line 468, in __getattr__
    a = getattr(file, name)
  File "/home/irrd/irrd-venv/lib/python3.8/tempfile.py", line 468, in __getattr__
    a = getattr(file, name)
AttributeError: '_io.BufferedReader' object has no attribute 'status'
```

**Comment by mxsasha** [comment]
This was almost certainly introduced by #409, will look into it.
